core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from main.views import pageNotFound


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

handler404 = pageNotFound

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "users"

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login_ajax/', views.LoginAjaxView.as_view(), name='login_ajax'),
    # path('logout/', logout_user, name='logout'),
    path('register_ajax/', views.RegisterAjaxView.as_view(), name='register'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'),
         name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'),
         name='invalid_verify'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('password_change_ajax/', views.ChangePasswordAjax.as_view(), name='password_change_ajax'),
    path('edit_user_ajax/', views.EditUserAjax.as_view(), name='edit_user_ajax'),
    path('edit_phone_ajax/', views.EditPhoneAjax.as_view(), name='edit_phone_ajax'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models



class User(AbstractUser):
    username = models.CharField(max_length=100, verbose_name='Имя пользователя')
    email = models.EmailField(('email address'),unique=True,)
    phone = models.CharField(max_length=100, verbose_name='Телефон')
    email_verify = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm
from .validator_phone import validate_phone_number

User = get_user_model()


class AuthenticationAjaxForm(forms.Form):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                'autocomplete': 'email',
                'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                'class': 'form-control',
                'id': 'password'
            }
        ),
    )


class RegisterAjaxForm(UserCreationForm):
    username = forms.CharField(
        label=_("Ваше имя"),
        min_length=3,
        max_length=254,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'email',
                'class': 'form-control'
            })
    )
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(
            attrs={'autocomplete': 'email', 'class': 'form-control'})
    )
    phone = forms.CharField(
        max_length=17,
        validators=[validate_phone_number],
        label='Телефон', widget=forms.TextInput(
            attrs={'type': 'tel', 'id': 'online_phone', 'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control login_input'}))
    password2 = forms.CharField(label='Повторите пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-control login_input'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "phone")
        # fields = ("username",)


class EditProfile(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        data = kwargs.pop('data', None)
        super(EditProfile, self).__init__(*args, **kwargs)
        if data:
            self.fields['username'] = forms.CharField(label='Имя', widget=forms.TextInput(
                attrs={'class': 'form-control form-value ', 'value': data.username, 'disabled': 'True'}))
            self.fields['phone'] = forms.Field(label='Телефон', widget=forms.TextInput(
                attrs={'type': 'tel', 'id': 'online_phone', 'class': 'form-control',
                       'pattern': '[+]{1}7 [(]{1}[0-9]{3}[)]{1} [0-9]{3} [0-9]{4}', 'value': data.phone,
                       'disabled': 'True'}))
            self.fields['email'] = forms.EmailField(label='E-mail', required=False, widget=forms.TextInput(
                attrs={'class': 'form-control form-value ', 'value': data.email, 'required': 'False',
                       'disabled': 'True'}))
            self.fields['password'] = forms.CharField(label='Пароь', required=False, widget=forms.PasswordInput(
                attrs={'class': 'form-control form-value ', 'value': '0000000000000', 'required': 'False',
                       'disabled': 'True'}))

    class Meta:
        model = User
        fields = ['username', 'phone', 'email']


class EditPhone(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        data = kwargs.pop('data', None)
        super(EditPhone, self).__init__(*args, **kwargs)
        # print(data)
        if data:
            self.fields['phone'] = forms.CharField(label='Телефон', widget=forms.TextInput(
                attrs={'type': 'tel', 'id': 'online_phone', 'class': 'form-control',
                       'pattern': '[+]{1}7 [(]{1}[0-9]{3}[)]{1} [0-9]{3} [0-9]{4}', 'placeholder': '+7 (999) 123 4455',
                       'value': data}))

    class Meta:
        model = get_user_model()
        fields = ['phone']


class ChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-value ', 'autocomplete': 'current-password', 'autofocus': True}),
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-value ', 'autocomplete': 'new-password', 'autofocus': True})
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-value ', 'autocomplete': 'new-password', 'autofocus': True})
    )


class EditUserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        data = kwargs.pop('data', None)
        super(EditUserForm, self).__init__(*args, **kwargs)
        # print(data)
        if data:
            self.fields['username'] = forms.CharField(label='Ваше имя', widget=forms.TextInput(
                attrs={'type': 'text', 'class': 'form-control', 'value': data}))

    class Meta:
        model = get_user_model()
        fields = ['username']

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.views import View
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth import get_user_model
from users.utils import send_email_for_verify
from users.forms import UserCreationForm, EditUserForm, EditPhone
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.utils.http import urlsafe_base64_decode
from django.template.loader import render_to_string
from django.urls import reverse
from users.forms import *
from django.contrib.auth.forms import PasswordChangeForm
import re

User = get_user_model()


# ==========================

# =================
class EmailVerify(View):

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            return redirect('home')
        return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


# ======================
class LoginAjaxView(View):

    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')

        if email and password:
            user = authenticate(email=email, password=password)
            check_email = User.objects.get(email=email)
            # print(f"check_email:{check_email.email_verify}")
            if user:
                if check_email.email_verify:
                    login(request, user)
                    return JsonResponse(
                        data={
                            'status': 201
                        },
                        status=200
                    )
                return JsonResponse(
                    data={
                        'status': 400,
                        'error': 'Email адрес не подтвержден, проверьте почту'
                    },
                    status=200
                )
            return JsonResponse(
                data={
                    'status': 400,
                    'error': 'Неверный Логин или Пароль'
                },
                status=200
            )
        return JsonResponse(
            data={
                'status': 400,
                'error': 'Введите логин и пароль'
            },
            status=200
        )


###############################################################

###############################################################
class RegisterAjaxView(View):

    def post(self, request):
        form = RegisterAjaxForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(email=request.POST.get('email'), password=request.POST.get('password1'))
            if user:
                # send_email_for_verify(request, request.user, request.POST.get('email'))
                login(request, user)
                send_email_for_verify(request, user)
                logout(request)
                return JsonResponse(data={'status': 201, 'response': 'Для подтверждения регистрации, проверьте почту.'},
                                    status=200)
        else:
            errors = form.errors.as_json()
            return JsonResponse(data={'status': 400, 'error': errors}, status=200)

        return JsonResponse(data={'status': 400, 'error': 'Ошибка'}, status=200)


###############################################################
# def logout_user(request):
#     if request.GET:
#         logout(request)
#     return redirect('home')
###################################################

class UserProfile(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'users/profile.html'
    model = User

    def get(self, request):
        data_user = get_object_or_404(User, email=request.user.email)
        form_user = EditUserForm(data=data_user.username)
        form = EditProfile(data=data_user)
        form_password = ChangeForm(user=request.user)
        # print(data_user.phone)
        form_phone = EditPhone(data=data_user.phone)
        context = {
            'title': 'Личный кабинет',
            'data_user': data_user,
            'form': form,
            'form_phone': form_phone,
            'form_password': form_password,
            'form_user': form_user,

        }
        return render(request, self.template_name, context)

    def post(self, request):
        print(request.POST)

        return render(request, self.template_name, {})


#########################################################
class ChangePasswordAjax(View):
    model = User

    def post(self, request):
        form_password = PasswordChangeForm(user=request.user, data=request.POST)
        if form_password.is_valid():
            form_password.save()
            return JsonResponse(data={'status': 201, 'response': "Успешно, войдите заново!"}, status=200)

        errors = form_password.errors.as_json()
        return JsonResponse(data={'status': 400, 'error': errors}, status=200)

    #########################################################


class EditUserAjax(View):
    # model = User
    def post(self, request):
        if 3 < len(request.POST.get('username')) < 30:
            # form_user = EditUserForm(request.POST)
            # if form_user.is_val?id():
            # form_user.save()
            User.objects.filter(email=request.user.email).update(username=request.POST.get('username'))
            return JsonResponse(data={'status': 201, 'response': 'Успешно'}, status=200)

        # errors = form_user.errors.as_json()
        return JsonResponse(data={'status': 400, 'error': 'Имя слишком короткое или длинное'}, status=200)
    # class EditUserAjax(View):


#     # model = User
#     def post(self, request):
#         form_user = EditUserForm(request.POST)
#         if form_user.is_valid():
#             # form_user.save()
#             User.objects.filter(email=request.user.email).update(username=request.POST.get('username'))
#             return JsonResponse(data={'status': 201},status=200)

#         errors = form_user.errors.as_json()
#         return JsonResponse(data={'status': 400, 'error': errors},status=200)
#########################################################
class EditPhoneAjax(View):
    def post(self, request):
        # form_phone = EditPhone(request.POST)
        reg = "^[+]{1}7 [(]{1}[0-9]{3}[)]{1} [0-9]{3} [0-9]{4}$"
        check_num = re.search(reg, request.POST.get('phone'))
        if check_num:
            User.objects.filter(email=request.user.email).update(phone=request.POST.get('phone'))
            return JsonResponse(data={'status': 201, 'response': 'Успешно'}, status=200)

        return JsonResponse(data={'status': 400, 'error': "Проверьте правильность номера"}, status=200)
#########################################################

users/templates/users/confirm_email.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <p>Пожалуйста проверьте свою почту чтобы завершить регистрацию</p>
    </div>
</div>
{% endblock %}

users/templates/users/invalid_verify.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <p>Ваша ссылка не корректна, залогиньтесь снова</p>
        
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}



{% block content %}

<p>Мы отправили вам по электронной почте инструкции по установке пароля, если существует учетная запись с указанным вами адресом электронной почты. Вы должны получить их в ближайшее время.</p>

<p>Если вы не получили электронное письмо, убедитесь, что вы ввели адрес, под которым зарегистрировались, и проверьте папку со спамом.</p>

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h3>Профиль пользователя</h3>
    <hr />
    <div class="row">
        <div class="col-sm-12">

            <table class="table">
                <tr>
                    <td>E-mail</td>
                    <td>{{form.email}}</td>
                    <td></td>
                </tr>

                <tr>
                    <td>Ваше имя</td>
                       <td>{{form.username}}</td>
                    <td><a href="#" data-bs-toggle="modal" data-bs-target="#usernameModal" class="btn"><svg
                        xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007cba"
                        class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path
                            d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z" />
                    </svg></a></td>
                </tr>


                <tr>
                    <td>Телефон</td>
                       <td>{{form.phone}}</td>
                    <td><a href="#" data-bs-toggle="modal" data-bs-target="#phoneModal" class="btn"><svg
                        xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007cba"
                        class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path
                            d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z" />
                    </svg></a></td>
                </tr>
                <tr>
                    <td>Пароль</td>
                    <td>{{form.password}}</td>
                   <td><a href="#" data-bs-toggle="modal" data-bs-target="#passwordModal" class="btn"><svg
                        xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007cba"
                        class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path
                            d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z" />
                    </svg></a></td>
                </tr>

            </table>

        </div><!--col-->
    </div><!--row-->
    
</div><!--container-->
{% include "users/profile_modal.html" %}
    {% endblock content %}

users/templates/users/profile_modal.html
<!--МОДАЛЬНЫЕ ОКНА-->

<!-- usernameModal -->
<div class="modal fade" id="usernameModal" tabindex="-1" aria-labelledby="usernameModalLabel"
aria-hidden="true">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="phoneModalLabel">Peдактирование имени</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"
                aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col">

                    <span style="color: gray;">Имя пользователя</span>
                </div><!--col-->
            </div><!--row-->
            <div class="row">
                <div class="col">
                    {% comment %} {% url "users:username_change" %} {% endcomment %}
                    <form method="post" action="{% url "users:edit_user_ajax" %}" id="form_username_edit">
                        {% csrf_token %}
                       <input type="hidden"  name="step" value="username">
                       <div class="alert alert-danger d-none error_username text-center" role="alert"></div>
                       <div class="alert alert-success d-none response text-center" role="alert"></div>
                       {{form_user.username}}
                       {% comment %} <input type="text" class="form-control form-value"> {% endcomment %}
                </div><!--col-->
            </div><!--row-->
            <div class="row">
                <div class="col">
                    <b>Введите имя</b>
                </div><!--col-->
            </div><!--row-->
        </div><!--modal-body-->
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
            <button type="submit" class="btn btn-dark">Сохранить</button>
           </form>
        </div>
    </div>
</div>
</div>
<!-- usernameModal END-->
             
<!-- phoneModal -->
<div class="modal fade" id="phoneModal" tabindex="-1" aria-labelledby="phoneModalLabel"
             aria-hidden="true">
             <div class="modal-dialog">
                 <div class="modal-content">
                     <div class="modal-header">
                         <h5 class="modal-title" id="phoneModalLabel">Peдактирование телефона</h5>
                         <button type="button" class="btn-close" data-bs-dismiss="modal"
                             aria-label="Close"></button>
                     </div>
                     <div class="modal-body">
                         <div class="row">
                             <div class="row">
                                 <span style="color: gray;">Мобильный телефон*</span>
                             </div>
                         </div>
                         <div class="row">
                             <div class="row">
                                <form method="post" action="{% url 'users:edit_phone_ajax' %}" id="form_phone_edit">
                                    {% csrf_token %}
                                    <input type="hidden"  name="step" value="phone">
                                    <div class="alert alert-danger d-none error_phone text-center" role="alert"></div>
                                    <div class="alert alert-success d-none response text-center" role="alert"></div>
                                     {{form_phone.phone}}
                             </div>
                         </div>
                         <div class="row">
                             <div class="col">
                                 <b>Введите номер телефона</b>
                             </div>
                         </div>
                     </div>
                     <div class="modal-footer">
                         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                         <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                     </div>
                 </div>
             </div>
         </div>
<!-- phoneModal END-->

<!-- passwordModal -->
<div class="modal fade" id="passwordModal" tabindex="-1" aria-labelledby="passwordModalLabel"
             aria-hidden="true">
             <div class="modal-dialog">
                 <div class="modal-content">
                     <div class="modal-header">
                         <h5 class="modal-title" id="passwordModalLabel">Изменение пароля</h5>
                         <button type="button" class="btn-close" data-bs-dismiss="modal"
                             aria-label="Close"></button>
                     </div>
                     <div class="modal-body">
                        
                <form method="post" action="{% url "users:password_change_ajax" %}" id="form_change_password">
                            {% csrf_token %}
                            <input type="hidden"  name="step" value="password">
                         
                         <div class="row">
                             <div class="col">
                                 <div class="alert alert-success d-none response text-center" role="alert"></div>
                                 <span style="color: gray;">Придумайте длинный пароль из букв и цифр, который вам
                                     будет легко запомнить, а другим — сложно угадать</span>
                             </div>
                         </div>
                         <div class="row mt-2">
                             <div class="col">
                                 <span style="color: gray;"><small>Текущий пароль*</small></span>
                             </div>
                         </div>
                         <div class="row ">
                             <div class="col">
                                 <div class="password">
                                    <div class="alert alert-danger d-none error_old text-center" role="alert"></div>
                                    {{form_password.old_password}}
                                     {% comment %} <input type="password" id="edit_password" name="password"
                                         class="form-control form-value" required> {% endcomment %}
                                     {% comment %} <a href="#" class="password-control"></a> {% endcomment %}
                                 </div>
                             </div>
                         </div>
                         <div class="row">
                             <div class="col">
                                 <span style="color: gray;"><small>Придумайте пароль*</small></span>
                             </div>
                         </div>
                         <div class="row ">
                             <div class="col">
                                 <div class="password">
                                    <div class="alert alert-danger d-none error_password2 text-center" role="alert"></div>
                                    {{form_password.new_password1}}
                                     {% comment %} <input type="password" id="password_new" name="password_new"
                                         class="form-control form-value" required> {% endcomment %}
                                     {% comment %} <a href="#" class="password-control_new"></a> {% endcomment %}
                                 </div>
                             </div>
                         </div>
                         <div class="row">
                             <div class="col">
                                 <span style="color: gray;"><small>Повтор нового пароля*</small></span>
                             </div>
                         </div>
                         <div class="row ">
                             <div class="col">
                                 <div class="password">
                                    {{ form_password.new_password2.errors }}
                                    {{form_password.new_password2}}
                                     {% comment %} <input type="password" id="password_re" name="password_re"
                                         class="form-control form-value" required> {% endcomment %}
                                     {% comment %} <a href="#" class="password-control_re"></a> {% endcomment %}
                                 </div>
                             </div>
                         </div>
                         <div class="row">
                            <div class="col"><label>
                                <input type='checkbox' id="show_pass_change"> <label for="show_pass">Показать пароль</label>
                            </lable>
                            </div>
                         </div>
                     

                     </div><!--modal body-->
                     <div class="modal-footer">
                         <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                         <button type="submit" class="btn btn-dark">Сохранить</button>
                     </form>
                     </div>
                 </div>
             </div>
         </div>
<!-- passwordModal END-->
<!--МОДАЛЬНЫЕ ОКНА END-->

users/templates/users/test.html
{% extends "base.html" %}

{% block content %}
<h1>TEST</h1>
{% endblock content %}

users/templates/users/verify_email.html
{% autoescape off %}

Здравствуйте, {{ user.get_username }}.
Пожалуйста, перейдите по ссылке, чтобы подтвердить регистрацию.
{{ http }}{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}

{% endautoescape %}