core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from main.views import pageNotFound


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

handler404 = pageNotFound

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = "users"

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login_ajax/', views.LoginAjaxView.as_view(), name='login_ajax'),
    # path('logout/', logout_user, name='logout'),
    path('register_ajax/', views.RegisterAjaxView.as_view(), name='register'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'),
         name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'),
         name='invalid_verify'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('password_change_ajax/', views.ChangePasswordAjax.as_view(), name='password_change_ajax'),
    path('edit_user_ajax/', views.EditUserAjax.as_view(), name='edit_user_ajax'),
    path('edit_phone_ajax/', views.EditPhoneAjax.as_view(), name='edit_phone_ajax'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

</head>

<body>

    <div class="wrapper">
        <header class="header">
            <div class="container">
                <div class="row">
                    <div class="col text-start"><!--1-->
                        <a href="tel:+79271536733" class="btn btn-success ">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                                <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.6 17.6 0 0 0 4.168 6.608 17.6 17.6 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.68.68 0 0 0-.58-.122l-2.19.547a1.75 1.75 0 0 1-1.657-.459L5.482 8.062a1.75 1.75 0 0 1-.46-1.657l.548-2.19a.68.68 0 0 0-.122-.58zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z"/>
                              </svg>
                            </a>
                            <span class="vis_elem"> +7 (927) 123 4567</span>
                    </div><!--col-->
                    <div class="col text-center d-none d-md-block">
                        <h3>Ваш Шиномонтаж</h3>
                    </div><!--col-->
                    <div class="col text-center d-block d-sm-none">
                        <span style="font-size: 15px;">Ваш Шиномонтаж</span>
                    </div><!--col-->
                    <div class="col text-end">
                        {% if user.is_authenticated %}
                        
                              <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Переключить навигацию">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                                  </svg>
                                  <span class="vis_elem"> {{user.email}}</span>
                              </button>
                              
                          
                        {% else %}
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Вход</button>
                            {% endif%}

                    </div><!--col-->
                </div><!--row-->
            </div><!--container-->
        </header><!--header-->



        



        <main class="main">
          
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/7361447.png' %}" width="80px" alt=""> </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Переключатель навигации">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Главная</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'pages' 'uslugi' %}">Услуги</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'pages' 'ceny' %}">Цены</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'contact' %}">Контакты</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>
     
            {%block content %}
            {% endblock %}
            {% include "users/modal.html" %}
           {% include "menu.html" %}
<!--=======================================================-->
</main>
<footer class="footer">
    <p>&copy; {{year}} Ваш Шиномонтаж</p>
</footer>
</div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/form.js' %}"></script>
    <script>

    </script>
    
</body>

</html>    

templates/menu.html
 <!-- ==================================== -->
 <div class="offcanvas offcanvas-end menu_title" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">{{user.email}}</h5>
      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
    </div>
    <div class="offcanvas-body">
      <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
        <hr>
          {% if request.user.is_superuser %}
          <li class="nav-item">
         <a class="nav-link" aria-current="page" href="{%url 'admin:index' %}"><i class="bi bi-person-square"></i> Админ</a>
        </li>
          {% endif %}
        <li class="nav-item">
         <a class="nav-link" aria-current="page" href="{%url 'users:profile' %}"><i class="bi bi-person"></i> Профиль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'calendar' %}"><i class="bi bi-calendar-week"></i> Мои записи</a>
        </li>
        <li class="nav-item">
          <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <i class='bi bi-box-arrow-left'></i> <input type="submit"  value="Выход" />
          </form>
          </li>
      </ul>
    
    </div><!--body-->
  </div>
</div>
<!--========================-->